serviceMaps:
 serviceName: User Service
 mappings:
 - version: 1.0
   name: PGR
   description: Persists grievance details in service table
   fromTopic: save-pgr-service
   isTransaction: true
   queryMaps:
    - query: INSERT INTO eg_pgr_service(tenantid, servicecode, servicerequestid, description, lat, "long", addressid, address, email, deviceid, accountid, firstname, lastname, phone, attributes, status, source, expectedtime, rating, feedback, landmark, createdby, createdtime, lastmodifiedby, lastmodifiedtime, category, slaendtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?);

      basePath: services.*
      jsonMaps:


       - jsonPath: $.services.*.tenantId

       - jsonPath: $.services.*.serviceCode

       - jsonPath: $.services.*.serviceRequestId

       - jsonPath: $.services.*.description

       - jsonPath: $.services.*.lat

       - jsonPath: $.services.*.long

       - jsonPath: $.services.*.addressId
       
       - jsonPath: $.services.*.address

       - jsonPath: $.services.*.email

       - jsonPath: $.services.*.deviceId

       - jsonPath: $.services.*.accountId

       - jsonPath: $.services.*.firstName

       - jsonPath: $.services.*.lastName

       - jsonPath: $.services.*.phone

       - jsonPath: $.services.*.attributes
         type: JSON
         dbType: JSONB

       - jsonPath: $.services.*.status

       - jsonPath: $.services.*.source

       - jsonPath: $.services.*.expectedTime

       - jsonPath: $.services.*.rating

       - jsonPath: $.services.*.feedback
       
       - jsonPath: $.services.*.landmark

       - jsonPath: $.services.*.auditDetails.createdBy

       - jsonPath: $.services.*.auditDetails.createdTime

       - jsonPath: $.services.*.auditDetails.lastModifiedBy

       - jsonPath: $.services.*.auditDetails.lastModifiedTime
       
       - jsonPath: $.services.*.category
       
       - jsonPath: $.services.*.slaEndTime


    - query: INSERT INTO eg_pgr_action(uuid, by, "when", action, status, comments, media, assignee, isinternal, tenantid, businesskey) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);

      basePath: actionInfo.*
      jsonMaps:

       - jsonPath: $.actionInfo.*.uuid
       
       - jsonPath: $.actionInfo.*.by

       - jsonPath: $.actionInfo.*.when
       
       - jsonPath: $.actionInfo.*.action

       - jsonPath: $.actionInfo.*.status

       - jsonPath: $.actionInfo.*.comments

       - jsonPath: $.actionInfo.*.media
         type: JSON
         dbType: JSONB

       - jsonPath: $.actionInfo.*.assignee

       - jsonPath: $.actionInfo.*.isInternal

       - jsonPath: $.actionInfo.*.tenantId

       - jsonPath: $.actionInfo.*.businessKey
       
    
       
    - query: INSERT INTO eg_pgr_address(uuid, housenoandstreetname, mohalla, landmark, latitude, longitude, city, tenantid, createdby, createdtime, lastmodifiedby, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);

      basePath: services.*
      jsonMaps:

       - jsonPath: $.services.*.addressDetail.uuid
       
       - jsonPath: $.services.*.addressDetail.houseNoAndStreetName

       - jsonPath: $.services.*.addressDetail.mohalla
       
       - jsonPath: $.services.*.addressDetail.landmark

       - jsonPath: $.services.*.addressDetail.latitude

       - jsonPath: $.services.*.addressDetail.longitude

       - jsonPath: $.services.*.addressDetail.city

       - jsonPath: $.services.*.addressDetail.tenantId

       - jsonPath: $.services.*.addressDetail.auditDetails.createdBy

       - jsonPath: $.services.*.addressDetail.auditDetails.createdTime

       - jsonPath: $.services.*.addressDetail.auditDetails.lastModifiedBy

       - jsonPath: $.services.*.addressDetail.auditDetails.lastModifiedTime
       

 - version: 1.0
   name: Asset
   description: Persists asset details in eg_asset table
   fromTopic: update-pgr-service
   isTransaction: true
   queryMaps:

    - query: UPDATE eg_pgr_service SET servicecode=?, description=?,lat=?, long=?, addressid=?, address=?, email=?, deviceid=?, firstname=?, lastname=?, phone=?, attributes=?,  status=?, source=?, expectedtime=?, feedback=?, rating=?, landmark=?, lastmodifiedby=?, lastmodifiedtime=?, category=?, slaendtime=? WHERE tenantid=? AND servicerequestid=?;

      basePath: services.*
      jsonMaps:

       - jsonPath: $.services.*.serviceCode

       - jsonPath: $.services.*.description

       - jsonPath: $.services.*.lat

       - jsonPath: $.services.*.long

       - jsonPath: $.services.*.addressId
       
       - jsonPath: $.services.*.address

       - jsonPath: $.services.*.email

       - jsonPath: $.services.*.deviceId

       - jsonPath: $.services.*.firstName

       - jsonPath: $.services.*.lastName

       - jsonPath: $.services.*.phone

       - jsonPath: $.services.*.attributes
         type: JSON
         dbType: JSONB

       - jsonPath: $.services.*.status

       - jsonPath: $.services.*.source

       - jsonPath: $.services.*.expectedTime

       - jsonPath: $.services.*.feedback

       - jsonPath: $.services.*.rating
       
       - jsonPath: $.services.*.landmark

       - jsonPath: $.services.*.auditDetails.lastModifiedBy

       - jsonPath: $.services.*.auditDetails.lastModifiedTime
       
       - jsonPath: $.services.*.category
       
       - jsonPath: $.services.*.slaEndTime

       - jsonPath: $.services.*.tenantId

       - jsonPath: $.services.*.serviceRequestId
       


    - query: INSERT INTO eg_pgr_action(uuid, by, "when", action, status, comments, media, assignee, isinternal, tenantid, businesskey) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);

      basePath: actionInfo.*
      jsonMaps:

       - jsonPath: $.actionInfo.*.uuid
       
       - jsonPath: $.actionInfo.*.by

       - jsonPath: $.actionInfo.*.when
       
       - jsonPath: $.actionInfo.*.action

       - jsonPath: $.actionInfo.*.status

       - jsonPath: $.actionInfo.*.comments

       - jsonPath: $.actionInfo.*.media
         type: JSON
         dbType: JSONB

       - jsonPath: $.actionInfo.*.assignee

       - jsonPath: $.actionInfo.*.isInternal

       - jsonPath: $.actionInfo.*.tenantId

       - jsonPath: $.actionInfo.*.businessKey

   
 - version: 1.0
   name: Autorouting
   description: Persists Autorouting details in the table
   fromTopic: save-autorouting-data
   isTransaction: true
   queryMaps:
    - query: INSERT INTO eg_pgr_autorouting_data(id, tenantid, autorouting, createdby, createdtime, lastmodifiedby, lastmodifiedtime, active) VALUES (?, ?, ?, ?, ?, ?, ?, ?);

      basePath: autoroutingmap
      jsonMaps:

       - jsonPath: $.autoroutingmap.id
       
       - jsonPath: $.autoroutingmap.tenantId

       - jsonPath: $.autoroutingmap.autorouting
         type: JSON
         dbType: JSONB

       - jsonPath: $.autoroutingmap.auditDetails.createdBy

       - jsonPath: $.autoroutingmap.auditDetails.createdTime

       - jsonPath: $.autoroutingmap.auditDetails.lastModifiedBy

       - jsonPath: $.autoroutingmap.auditDetails.lastModifiedTime
       
       - jsonPath: $.autoroutingmap.active
       
       
 - version: 1.0
   name: Autorouting Update
   description: Update autorouting details in the table
   fromTopic: update-autorouting-data
   isTransaction: true
   queryMaps:

    - query: UPDATE eg_pgr_autorouting_data SET autorouting=?, lastmodifiedby=?, lastmodifiedtime=?, active=? WHERE id=? AND tenantid=?;

      basePath: autoroutingmap
      jsonMaps:

       - jsonPath: $.autoroutingmap.autorouting
         type: JSON
         dbType: JSONB

       - jsonPath: $.autoroutingmap.auditDetails.lastModifiedBy

       - jsonPath: $.autoroutingmap.auditDetails.lastModifiedTime
       
       - jsonPath: $.autoroutingmap.active
       
       - jsonPath: $.autoroutingmap.id
       
       - jsonPath: $.autoroutingmap.tenantId
       
 - version: 1.0
   name: Discription Report data Dump
   description: Discription Report data Dump
   fromTopic: dump-discription-data
   isTransaction: true
   queryMaps:

    - query: INSERT INTO public.eg_pgr_discription_report(   lastassignedto, servicecode, locality, complaintno, date, name,   phone, landmark, address, description, complaintraisedby, slahours,   lastactiondate, status, autoescalated, createdtime,department,servicerequestid,tenantid,slaendtime,source)     VALUES (?, ?, ?, ?, ?, ?,   ?, ?, ?, ?, ?, ?,   ?, ?, ?, ?,?,?,?,?,?)
              ON CONFLICT (servicerequestid,tenantid) DO UPDATE SET lastassignedto=?, servicecode=?, locality=?, complaintno=?, date=?, name=?, phone=?, landmark=?, address=?, description=?, complaintraisedby=?, slahours=?, lastactiondate=?, status=?, autoescalated=?, department=?, 
       servicerequestid=?, tenantid=?, createdtime=? ,slaendtime=?,source=?

      basePath: discriptionReport
      jsonMaps:

       - jsonPath: $.discriptionReport.lastassignedto
       - jsonPath: $.discriptionReport.servicecode
       - jsonPath: $.discriptionReport.locality       
       - jsonPath: $.discriptionReport.complaintNo       
       - jsonPath: $.discriptionReport.date       
       - jsonPath: $.discriptionReport.name        
       - jsonPath: $.discriptionReport.phone
       - jsonPath: $.discriptionReport.landmark
       - jsonPath: $.discriptionReport.address       
       - jsonPath: $.discriptionReport.description       
       - jsonPath: $.discriptionReport.complaintraisedby       
       - jsonPath: $.discriptionReport.slaHours       
       - jsonPath: $.discriptionReport.lastactiondate       
       - jsonPath: $.discriptionReport.status       
       - jsonPath: $.discriptionReport.autoescalated       
       - jsonPath: $.discriptionReport.createdtime       
       - jsonPath: $.discriptionReport.department       
       - jsonPath: $.discriptionReport.servicerequestid       
       - jsonPath: $.discriptionReport.tenantid   
       - jsonPath: $.discriptionReport.slaendtime
       - jsonPath: $.discriptionReport.source      
       - jsonPath: $.discriptionReport.lastassignedto
       - jsonPath: $.discriptionReport.servicecode
       - jsonPath: $.discriptionReport.locality       
       - jsonPath: $.discriptionReport.complaintNo       
       - jsonPath: $.discriptionReport.date       
       - jsonPath: $.discriptionReport.name        
       - jsonPath: $.discriptionReport.phone
       - jsonPath: $.discriptionReport.landmark
       - jsonPath: $.discriptionReport.address       
       - jsonPath: $.discriptionReport.description       
       - jsonPath: $.discriptionReport.complaintraisedby       
       - jsonPath: $.discriptionReport.slaHours       
       - jsonPath: $.discriptionReport.lastactiondate       
       - jsonPath: $.discriptionReport.status       
       - jsonPath: $.discriptionReport.autoescalated              
       - jsonPath: $.discriptionReport.department       
       - jsonPath: $.discriptionReport.servicerequestid       
       - jsonPath: $.discriptionReport.tenantid      
       - jsonPath: $.discriptionReport.createdtime
       - jsonPath: $.discriptionReport.slaendtime
       - jsonPath: $.discriptionReport.source
   
